---
- name: Converge
  hosts: all
  become: true
  vars:
    - galera_ssl: false
    - mysql_ssl: false
  pre_tasks:
    - name: Install needed packages for ansible
      yum:
        name:
          - iproute
  roles:
    - role: ansible-role-galera
