---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: libvirt
    type: libvirt
    options:
      menory: 1024
      cpus: 1
    driver: kvm
lint:
  name: yamllint
  enabled: true
platforms:
  - name: node1
    box: centos/7
  - name: node2
    box: centos/7
  - name: node3
    box: centos/7
provisioner:
  name: ansible
  lint:
    name: ansible-lint
    enabled: true
    options:
      exclude:
        - molecule/default/roles/ansible-hardening
verifier:
  name: testinfra
  lint:
    name: flake8
