---
- name: Prepare
  hosts: all
  gather_facts: true
  become: true
  vars:
    packages:
      redhat:
        - python2-pip
        - python-setuptools
      update_all: false
    repositories:
      redhat:
        - { url: 'https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm' }
  pre_tasks:
    - import_role:
        name: ansible-role-repositories
    - import_role:
        name: ansible-role-packages
...
